def info():
    print("Cooking Game®")
    print("Made by nikeedev(Nikita)")
    print("Copyright ©2022")
    print("This game is made completely by hand, and no tutorials have been used.")
    print("Game code can be changed, but without asking owner(nikeedev),")
    print("you are not following rules and may cause in problems.")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("Contact me here:")
    print("Discord(Spamming me causes to block you from support): nikeedev#8874")
    print("Github: nikeedev(Use issue report function in repo)")
    print("")


def update():
    print("Update: Typos fixing")
    print("")
    print("Version: v.0.6.4")
    print("")
    print("New:")
    print("")
    print("Fixed typos, and words to make it easier for you to read!")
    print(" (that wasn't small sentence!) ")
    print("")
    print("")
    print("")